name: Publish Package

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kirjaswappi'
          always-auth: true

      - name: Configure GitHub Bot Identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install Dependencies
        run: npm ci

      - name: Extract Release Version
        run: echo "RELEASE_VERSION=$(echo $GITHUB_REF | sed -e 's/refs\/tags\/v//')" >> $GITHUB_ENV

      - name: Update package.json
        run: npm version "$RELEASE_VERSION" --no-git-tag-version --allow-same-version

      - name: Publish Package to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
